base:
  base_gzh_url: https://api.weixin.qq.com
  base_wyn_url: https://api.apiopen.top
  base_php_url: https://analysis-api.test.ztosys.com

log:
  log_name: logs_
  log_level: info
  log_format: '[%(asctime)s] % (filename)s->%(funcName)s line:%(lineno)d [level]'